Repository nimblehq/nimble-crypto-ios, pull requests merged in 2023-01, with the labels that each got.

#77 [#76] [Chore] Update SourceryPlugin to clear previously-generated codes before generating new one
  CryptoPrices/Sources/BuildTools/Plugins/SourceryPlugin/SourceryPlugin.swift
Labels: type : chore

#81 [#11] [Integrate] As a user, when selecting a coin on the Home screen, I can see the coin’s header information on the Detail screen
  CryptoPrices/Sources/App/AppView/AppCoordinator.swift
  CryptoPrices/Sources/App/AppView/AppView.swift
  CryptoPrices/Sources/App/DependenciesInjection/Container+Injection.swift
  CryptoPrices/Sources/MyCoin/Package.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/CoinDetailItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinState.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinTests.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
Labels: type : feature

#83 [Chore] Bump version to 0.6.0
  CryptoPrices.xcodeproj/project.pbxproj
Labels: type : chore

#84 [#44] [UI] As a user, I can see the coin’s statistics on the Detail screen
  CryptoPrices/Sources/MyCoin/Package.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Localization/Strings.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/CoinDetailItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  swiftgen.yml
Labels: type : feature

#80 [#59] [Chore] Use Swift package plugin to support swiftgen generate code for resources
  CryptoPrices.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CryptoPrices/Sources/Home/Package.swift
  CryptoPrices/Sources/Home/Sources/Home/Localization/Strings.swift
  CryptoPrices/Sources/Home/Sources/Home/swiftgen.yml
  CryptoPrices/Sources/MyCoin/Package.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Localization/Strings.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/swiftgen.yml
  CryptoPrices/Sources/Styleguide/Package.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Colors.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Fonts.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Images.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/swiftgen.yml
  Makefile
  README.md
  fastlane/Helpers/Test.swift
  swiftgen.yml
Labels: type : chore

#87 [#37] [UI] As a user, I can see the chart on the Detail screen
  CryptoPrices.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CryptoPrices/Sources/MyCoin/Package.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/View+ReadSize.swift
Labels: type : feature

#86 [#41] [UI] As a user, I can see a timeframe bar on the Detail screen
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameSection.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Resources/Assets/Colors.xcassets/osloGray.colorset/Contents.json
Labels: type : feature

#92 [#59] [Chore] Use Swift package plugin to support swiftgen generate code for resources - part 2
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  fastlane/Helpers/Build.swift
Labels: type : chore

#91 Release 0.6.0
  CryptoPrices.xcodeproj/project.pbxproj
  CryptoPrices.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  CryptoPrices/Sources/Home/Package.swift
  CryptoPrices/Sources/Home/Sources/Home/CommonViews/HomeHeader.swift
  CryptoPrices/Sources/Home/Sources/Home/CommonViews/Section.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeView.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeViewModel.swift
  CryptoPrices/Sources/Home/Sources/Home/Localization/Strings.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsSectionView/MyCoinSection.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItemView.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinsView.swift
  CryptoPrices/Sources/Home/Sources/Home/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsSectionView/TrendingCoinSection.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItemView.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinsView.swift
  CryptoPrices/Sources/Home/Sources/Home/WalletStatisticView/WalletStatisticView.swift
  CryptoPrices/Sources/Home/Sources/Home/swiftgen.yml
  CryptoPrices/Sources/Home/Tests/HomeTests/HomeViewModelSpec.swift
  CryptoPrices/Sources/MyCoin/Package.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/CoinDetailItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/swiftgen.yml
  CryptoPrices/Sources/Styleguide/Package.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Colors.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Fonts.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Generated/Images.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/View+ReadSize.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Resources/Assets/Colors.xcassets/osloGray.colorset/Contents.json
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/View+Extensions/View+RenderIf.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/swiftgen.yml
  Makefile
  README.md
  fastlane/Helpers/Build.swift
  fastlane/Helpers/Test.swift
  swiftgen.yml
Labels: type : release

#90 [Chore] Bump version to 0.7.0
  CryptoPrices.xcodeproj/project.pbxproj
Labels: type : chore

#93 [#46] [UI] As a user, I can see the Buy & Sell buttons on the Detail screen
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/ButtonStyles/PrimaryButtonStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/ButtonStyles/SecondaryButtonStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/Section.swift
Labels: type : feature

#94 [#38] [Integrate] As a user, I can see the chart on the Detail screen
  CryptoPrices/Sources/App/DependenciesInjection/Container+Injection.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockCoinDetail.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockImage.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockMarketData.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockUSDDecimal.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockUSDDouble.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/ChartDataPointUIModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/FontConvertible/FontConvertible+TextStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/FormatStyle/FormatStyle+Extensions.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/Views/View+ReadSize.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/Views/View+RenderIf.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/FormatStyle/DollarCurrencyFormatStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/FormatStyle/PercentageFormatStyle.swift
Labels: type : feature

#96 [#45] [Integrate] As a user, I can see the coin’s statistics on the Detail screen
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockCoinDetail.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockMarketData.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
Labels: type : feature

#99 [#43] [Integrate] As a user, I can see timeframe bar on the Detail screen
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameSection.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
Labels: type : feature

#97 [#14] [Integrate] As a user, I can see the coin’s current price on the Detail screen
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItemView.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItemView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CurrentPriceSectionView/CurrentPriceSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/CoinDetailItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/PercentageView.swift
Labels: type : feature

#98 [#63] [Integrate] As a user, I can pull to refresh data on the Detail screen
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameSection.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
Labels: type : feature

#100 Release - 0.7.0
  CryptoPrices.xcodeproj/project.pbxproj
  CryptoPrices/Sources/App/DependenciesInjection/Container+Injection.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/MockCoinDetail/MockMarketData.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockCoinDetail.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockImage.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockMarketData.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockUSDDecimal.swift
  CryptoPrices/Sources/Domain/Sources/DomainTestHelpers/Mocks/MockCoinDetail/MockUSDDouble.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeView.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/MyCoinsView/MyCoinItemView.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItem.swift
  CryptoPrices/Sources/Home/Sources/Home/TrendingCoinsView/TrendingCoinItemView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/ChartDataPointUIModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/ChartSectionView/PriceLineChartView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CoinStatisticsSection/CoinStatisticsSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CurrentPriceSectionView/CurrentPriceSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/CoinDetailItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/Resources/en.lproj/Localizable.strings
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameItem.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/TimeFrameSectionView/TimeFrameSection.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/ButtonStyles/PrimaryButtonStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/ButtonStyles/SecondaryButtonStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/PercentageView.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/Section.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/FontConvertible/FontConvertible+TextStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/FormatStyle/FormatStyle+Extensions.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/Views/View+ReadSize.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Extensions/Views/View+RenderIf.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/FormatStyle/DollarCurrencyFormatStyle.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/Helpers/FormatStyle/PercentageFormatStyle.swift
Labels: type : release

#104 [Chore] Bump version to 0.8.0
  CryptoPrices.xcodeproj/project.pbxproj
Labels: type : chore

#105 [#102] [Chore] Add the App Icon
  CryptoPrices/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  CryptoPrices/Resources/Assets.xcassets/AppIcon.appiconset/app-icon.png
  README.md
Labels: type : chore

#106 [#103] [UI+Integrate] Display a loading spinner while fetching the data
  CryptoPrices.xcodeproj/project.pbxproj
  CryptoPrices/Sources/App/AppView/AppState.swift
  CryptoPrices/Sources/App/AppView/AppView.swift
  CryptoPrices/Sources/App/DependenciesInjection/Container+Injection.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeView.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeViewModel.swift
  CryptoPrices/Sources/Home/Tests/HomeTests/HomeViewModelSpec.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/CircularProgressView.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/Spinner.swift
Labels: type : feature

#107 [#101] [Chore] Update the information about the app
  README.md
Labels: type : chore

#108 [#14] [Integrate] As a user, I can see the coin’s current price on the Detail screen - part 2
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CurrentPriceSectionView/CurrentPriceSection.swift
Labels: type : feature

#109 Release - 0.8.0
  CryptoPrices.xcodeproj/project.pbxproj
  CryptoPrices/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  CryptoPrices/Resources/Assets.xcassets/AppIcon.appiconset/app-icon.png
  CryptoPrices/Sources/App/AppView/AppState.swift
  CryptoPrices/Sources/App/AppView/AppView.swift
  CryptoPrices/Sources/App/DependenciesInjection/Container+Injection.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeView.swift
  CryptoPrices/Sources/Home/Sources/Home/HomeView/HomeViewModel.swift
  CryptoPrices/Sources/Home/Tests/HomeTests/HomeViewModelSpec.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/CurrentPriceSectionView/CurrentPriceSection.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinView.swift
  CryptoPrices/Sources/MyCoin/Sources/MyCoin/MyCoinView/MyCoinViewModel.swift
  CryptoPrices/Sources/MyCoin/Tests/MyCoinTests/MyCoinViewModelSpec.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/CircularProgressView.swift
  CryptoPrices/Sources/Styleguide/Sources/Styleguide/CommonViews/Spinner.swift
  README.md
Labels: type : release
